name: Deploy to Server

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan locadesk.com >> ~/.ssh/known_hosts

    - name: Fetch full history
      run: git fetch --unshallow

    - name: Push to remote server
      run: |
        git remote add deploy ssh://deploy@lucaspolloni.com:/opt/todo/prod/app.git
        git push deploy prod:master
